nelmio_api_doc:
    documentation:
        components:
                securitySchemes:
                    Bearer:
                        type: http
                        scheme: bearer
                        bearerFormat: JWT
        security:
            - bearer: []
        servers:
          - url: http://localhost:8000
            description: API on localhost
          - url: https://api.la-guilde-des-seigneurs.com
            description: API on production
        info:
            title: La Guilde des Seigneurs
            description: API utilisée pour La Guilde des Seigneurs
            version: "1"
    areas: # to filter documented areas
        path_patterns:
            - ^/((?!api|_error).*$)
